# Generated by Django 3.2.4 on 2021-06-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=80, verbose_name='Nombre categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('codProducto', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo producto')),
                ('nomProducto', models.CharField(max_length=15, verbose_name='Nombre producto')),
                ('imagen', models.ImageField(default='sinfoto.png', upload_to='images/', verbose_name='Imagen producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio Producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
