# Generated by Django 3.2.4 on 2021-07-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_nomproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('cuenta', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Cuenta')),
                ('rut', models.CharField(max_length=80, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('password', models.CharField(max_length=80, verbose_name='Contraseña')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='producto',
            name='descFich',
            field=models.CharField(max_length=200, null=True, verbose_name='descFich'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descFichCom',
            field=models.CharField(max_length=500, null=True, verbose_name='descFichCom'),
        ),
    ]
