# Generated by Django 3.2.4 on 2021-07-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210702_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descFich',
            field=models.CharField(max_length=200, null=True, verbose_name='Descripcion Ficha'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descFichCom',
            field=models.CharField(max_length=500, null=True, verbose_name='Descripcion Ficha Completa'),
        ),
    ]
