# Generated by Django 3.2.4 on 2021-06-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
