# Generated by Django 3.2.4 on 2021-06-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cuentaUsuario',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='emailUsuario',
            field=models.CharField(max_length=50, verbose_name='email'),
        ),
    ]
