# Generated by Django 3.2.4 on 2021-06-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210630_0145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
