# Generated by Django 3.2.4 on 2021-06-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cuentaUsuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cuenta')),
                ('passUsuario', models.CharField(max_length=15, verbose_name='Password')),
                ('emailUsuario', models.CharField(max_length=50, verbose_name='email')),
                ('nomUsuario', models.CharField(max_length=50, verbose_name='Nombre')),
                ('celUsuario', models.CharField(max_length=50, verbose_name='Celular')),
            ],
        ),
    ]
